### ISSUE TITLE
Null entity on multiple-select list filter

### ISSUE THREAD

**Issue by AaronGilMartinez** [openeuropa/oe_list_pages#103]
Dear colleagues,

I've found an issue in the component that throws a PHP error.

The error is related to multi-select filter and is triggered when the multi-select tries to load an entity and returns a NULL.

Steps to reproduce:

1. Install clean
2. Enable field UI
3. Enable extra field
4. Enable Database Search
5. Clear cache
6. Add content types: _test_ and _sub-test_
9. Add reference field in _test_ pointing to _sub-test_
10. Show extra fields on list content type display: _results, filters, ..._
11. Add a search API server: _default_
13. Add a content index with the content type _test_ on the _default_ server.
16. Add a field to the index using the referenced field _sub-test_ title
18. Add a facet for the title with the previous field and set the widget to multi-select.
23. Create content for sub-tests and tests
24. Create a list page with the _test_ bundle and filter.

Now if a user tries to filter the list page on view the site crashes.

Proposed solution:
https://github.com/openeuropa/oe_list_pages/pull/102

Could you review this, please?

Thanks!
BR,
Aaron Gil

**Comment by imanoleguskiza** [comment]
Issue can be reproduced if you try to filter using an entity that does not exist anymore. While difficult to achieve a user could potentially save a url with certain filters on and cause this.
