### ISSUE TITLE
Error after creating a list_page

### ISSUE THREAD

**Issue by strusos** [openeuropa/oe_list_pages#118]
I have the following error after creating a List page with:
Source Entity Type: Content
Source Bundle: News

InvalidArgumentException: Field oe_summary is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of /home/ec2-user/environment/fisma-edfp-reference/web/core/lib/Drupal/Core/Entity/ContentEntityBase.php).

Any ideas?

**Comment by strusos** [comment]
Hello @randomnessdev . The issue was resolved by re-using the "oe_summary" field in the oe_list_page content type.

**Comment by imanoleguskiza** [comment]
Closing since issue was fixed.
