### ISSUE TITLE
How can I set sorting criteria for list pages?

### ISSUE THREAD

**Issue by sotiropo** [openeuropa/oe_list_pages#125]
How can we set sorting criteria for list pages? For example, if I want to order listed items by descending "Authored on" date.

**Comment by imanoleguskiza** [comment]
Hi @sotiropo, the complete functionality will be provided by https://github.com/openeuropa/oe_list_pages/pull/137. However you can already set a default sort in the content type definition: https://github.com/openeuropa/oe_list_pages/blob/master/tests/modules/oe_list_pages_filters_test/config/install/node.type.content_type_one.yml#L13
